-- Real Production Schema for Deadlock Analysis
-- Tables: KCR_CURRENT_LIMIT, KCR_CURRENT_OUTSTANDING_SYSTEM

-- Drop existing tables
DROP TABLE KCR_CURRENT_OUTSTANDING_SYSTEM;
DROP TABLE KCR_CURRENT_LIMIT;

-- Main table: KCR_CURRENT_LIMIT
CREATE TABLE KCR_CURRENT_LIMIT (
    CURRENT_LIMIT_ID BIGINT NOT NULL PRIMARY KEY,
    PRODUCT_TYPE_ID VARCHAR(50),
    CPTY_REFERENCE VARCHAR(100),
    LIMIT_BEHAVIOR CHAR(2),
    IS_REVIEW_NEEDED SMALLINT DEFAULT 0,
    LIMIT_AMOUNT DECIMAL(18,2),
    CURRENCY_CODE VARCHAR(3),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    STATUS VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Outstanding system table
CREATE TABLE KCR_CURRENT_OUTSTANDING_SYSTEM (
    OUTSTANDING_ID BIGINT NOT NULL PRIMARY KEY,
    CURRENT_LIMIT_ID BIGINT NOT NULL,
    PRODUCT_TYPE_ID VARCHAR(50),
    CPTY_REFERENCE VARCHAR(100),
    OUTSTANDING_AMOUNT DECIMAL(18,2),
    TRANSACTION_DATE DATE,
    SYSTEM_ID VARCHAR(50),
    STATUS VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX idx_limit_product ON KCR_CURRENT_LIMIT(PRODUCT_TYPE_ID);
CREATE INDEX idx_limit_cpty ON KCR_CURRENT_LIMIT(CPTY_REFERENCE);
CREATE INDEX idx_limit_behavior ON KCR_CURRENT_LIMIT(LIMIT_BEHAVIOR);
CREATE INDEX idx_limit_review ON KCR_CURRENT_LIMIT(IS_REVIEW_NEEDED);
CREATE INDEX idx_limit_id ON KCR_CURRENT_LIMIT(CURRENT_LIMIT_ID);

CREATE INDEX idx_out_limit_id ON KCR_CURRENT_OUTSTANDING_SYSTEM(CURRENT_LIMIT_ID);
CREATE INDEX idx_out_product ON KCR_CURRENT_OUTSTANDING_SYSTEM(PRODUCT_TYPE_ID);
CREATE INDEX idx_out_cpty ON KCR_CURRENT_OUTSTANDING_SYSTEM(CPTY_REFERENCE);

-- Grant permissions
GRANT ALL ON KCR_CURRENT_LIMIT TO PUBLIC;
GRANT ALL ON KCR_CURRENT_OUTSTANDING_SYSTEM TO PUBLIC;
